apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1  # Number of pods to run (adjust as needed)
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: sajidlone/ec2flask  # The image built from your Dockerfile (could be from DockerHub or a private registry)
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80  # External port to expose (could be 80 or any port)
      targetPort: 8080  # The internal container port exposed by Flask app
  type: LoadBalancer  # This can be NodePort if you're running locally or ClusterIP for internal access